name: microphone_platform_interface
description: Platform interface package for the microphone plugin.
version: 0.0.1
homepage: >-2
  https://github.com/creativecreatorormaybenot/microphone/tree/master/microphone_platform_interface

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.2
  pedantic: ^1.9.2
